spin_version = "1"
authors = ["Quinn Millican <quinnmillican@gmail.com>"]
description = "this service returns the \"/lowercase\" endpoint"
name = "challenge-2-lowercase"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "challenge-2-lowercase"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
